spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/isto_e_pousada
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Usado para criar e atualizar o esquema do banco de dados automaticamente. Pode ser 'none', 'validate', 'update', 'create', 'create-drop'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Define o dialeto SQL usado pelo Hibernate para PostgreSQL
    show-sql: true  # Para mostrar as consultas SQL geradas no console
    generate-ddl: true  # Para gerar as tabelas automaticamente com base nas entidades
    open-in-view: false  # Desativa o padrão de manter a sessão aberta durante a view
