package principals.tools;

import javax.swing.*;

public class Icones {
    public static ImageIcon logo = new ImageIcon("src/main/resources/icons/pousada_logo.png");
    public static ImageIcon dashboard = new ImageIcon("src/main/resources/icons/menu/dashboard.png");
    public static ImageIcon quartos = new ImageIcon("src/main/resources/icons/menu/rooms.png");
    public static ImageIcon entradas = new ImageIcon("src/main/resources/icons/menu/entry.png");
    public static ImageIcon pernoites = new ImageIcon("src/main/resources/icons/menu/overnight.png");
    public static ImageIcon relatorios = new ImageIcon("src/main/resources/icons/menu/reports.png");
    public static ImageIcon clientes = new ImageIcon("src/main/resources/icons/menu/customers.png");
    public static ImageIcon itens = new ImageIcon("src/main/resources/icons/menu/itens.png");
    public static ImageIcon reservas = new ImageIcon("src/main/resources/icons/menu/reservations.png");
    public static ImageIcon preco = new ImageIcon("src/main/resources/icons/menu/price.png");
    public static ImageIcon calendario = new ImageIcon("src/main/resources/icons/calendar.png");
    public static ImageIcon usuarios = new ImageIcon("src/main/resources/icons/users.png");
    public static ImageIcon desconto = new ImageIcon("src/main/resources/icons/desconto.png");
    public static ImageIcon sacola = new ImageIcon("src/main/resources/icons/sacola.png");
    public static ImageIcon diarias_quantidade = new ImageIcon("src/main/resources/icons/diarias_quantidade.png");
    public static ImageIcon esquerda = new ImageIcon("src/main/resources/icons/esquerda.png");
    public static ImageIcon direita = new ImageIcon("src/main/resources/icons/direita.png");
    public static ImageIcon sacola_branca = new ImageIcon("src/main/resources/icons/sacola branca.png");
    public static ImageIcon pessoas_branco = new ImageIcon("src/main/resources/icons/pessoas_branco.png");
    public static ImageIcon pagamento = new ImageIcon("src/main/resources/icons/pagamento.png");
    public static ImageIcon usuario = new ImageIcon("src/main/resources/icons/usuario_solo.png");
    public static ImageIcon bancario = new ImageIcon("src/main/resources/icons/bancario.png");
    public static ImageIcon cartao = new ImageIcon("src/main/resources/icons/cartao.png");
    public static ImageIcon dinheiro = new ImageIcon("src/main/resources/icons/dinheiro.png");
    public static ImageIcon pix = new ImageIcon("src/main/resources/icons/pix.png");
    public static ImageIcon user_sem_foto = new ImageIcon("src/main/resources/icons/user_sem_foto_2.jpg");
    public static ImageIcon user_sem_foto_feminino = new ImageIcon("src/main/resources/icons/user_sem_foto_feminino.jpg");
    public static ImageIcon user_funcionario = new ImageIcon("src/main/resources/icons/menu/user.png");
    public static ImageIcon rede = new ImageIcon("src/main/resources/icons/rede.png");
    public static ImageIcon cama_casal = new ImageIcon("src/main/resources/icons/cama_casal.png");
    public static ImageIcon cama_solteiro = new ImageIcon("src/main/resources/icons/cama_solteiro.png");
    public static ImageIcon beliche = new ImageIcon("src/main/resources/icons/beliche.png");
    public static ImageIcon linked = new ImageIcon("src/main/resources/icons/chainn.png");
    public static ImageIcon plus = new ImageIcon("src/main/resources/icons/plus_icon.png");
    public static ImageIcon search = new ImageIcon("src/main/resources/icons/search.png");
    public static ImageIcon cash_out = new ImageIcon("src/main/resources/icons/cash out.png");
    public static ImageIcon card = new ImageIcon("src/main/resources/icons/card.png");
    public static ImageIcon saved = new ImageIcon("src/main/resources/icons/check.gif");
    public static ImageIcon cash = new ImageIcon("src/main/resources/icons/cash.png");
    public static ImageIcon bank = new ImageIcon("src/main/resources/icons/bank.png");
    public static ImageIcon check = new ImageIcon("src/main/resources/icons/check.png");
    public static ImageIcon warning = new ImageIcon("src/main/resources/icons/warning.png");
    public static ImageIcon error = new ImageIcon("src/main/resources/icons/error.png");
    public static ImageIcon previous = new ImageIcon("src/main/resources/icons/previous.png");
    public static ImageIcon forward = new ImageIcon("src/main/resources/icons/forward.png");
    public static ImageIcon filter_gray = new ImageIcon("src/main/resources/icons/filter_gray.png");
}
